### ISSUE TITLE
Language Modeling?

### ISSUE THREAD

**Issue by srush** [TrentBrick/PyTorchDiscreteFlows#1]
Curious if you were able to get the lm examples from the paper working.

**Comment by TrentBrick** [comment]
I haven't tried at this point! Honestly haven't been able to reproduce any figures from the paper yet... I got pretty sick/busy. Need to get the scale=True functionality working. Then will be reaching out to the authors about reproduction issues (the scale=True should not be a barrier to reproducing the first few toy examples either...). Expect some more pushes in the next week or so!

**Comment by srush** [comment]
:+1:

**Comment by TrentBrick** [comment]
@srush I just pushed another notebook trying to reproduce Figure 2 and failing (also updated the README with this). This is what I am going to reach out to the authors about. I think the initialization of the latent space is pretty non-trivial. 

This is what I am first going to reach out to the authors about. Have you managed to reproduce any parts of the paper?

**Comment by srush** [comment]
Nope, we had an interned who couldn't. It's such a good paper, I was hoping you had better luck.

**Comment by JoeHEZHAO** [comment]
Good work. Appreicate your effort.

**Comment by jinzijian** [comment]
I am also very interested in Language Model and hope can help you to finish it; Would U like to contact me and talk me more about this project

**Comment by TrentBrick** [comment]
@jinzijian thanks for your interest and yes happy to discuss getting this code to reproduce the figures. You can email me at brickentrenton@gmail.com

**Comment by TrentBrick** [comment]
Figure 2 has now been successfully replicated and the TODOs updated. One step closer to replicating the language modelling :)

**Comment by srush** [comment]
Very cool!

**Comment by srush** [comment]
Was this replicated?

**Comment by TrentBrick** [comment]
Sorry for my terribly slow reply, this has not yet been replicated but I think all the components should now be there?

**Comment by srush** [comment]
Hmm, okay. I mean I can write the code for this model. But I can't make it work...

**Comment by TrentBrick** [comment]
Using the code from this repo? What seems to not be working?

**Comment by srush** [comment]
Well in short, the perplexity was not good. But I guess that is expected if no one has tried it yet.

**Comment by TrentBrick** [comment]
@srush would you be willing to add your code attempting to replicate this to the repo here? Someone else may be able to figure out and replicate the results then?
