### ISSUE TITLE
Did not find DiscreteFlowDemo.ipynb

### ISSUE THREAD

**Issue by yalidu** [TrentBrick/PyTorchDiscreteFlows#3]
Hi, Trent, 

Thanks for your implementation! I am trying to go through the code, but did not find 'DiscreteFlowDemo.ipynb' which is stated in the Readme.md. Also 'Figure2Replication.ipynb' causes dead kernel.

Could you help to fix this? Thanks! 

Best,
Yali

**Comment by TrentBrick** [comment]
Hi @yalidu apologies for these issues. I need to update the README to remove the 'DiscreteFlowDemo.ipynb' it has been subsumed by the 'Figure2Replication.ipynb'.

I'm not sure why you are getting a dead kernel, however. How much RAM do you have and which model are you trying to use? 

The default autoregressive MADE model is probably the most memory intensive. 

Try the bipartite model by making: 
`disc_layer_type = 'bipartite'`

If this works then next uncomment the embedding layer and comment out the MADE layer like so and see if that also works:

```
layer = EmbeddingLayer([batch_size, sequence_length, vocab_size], output_size=vocab_size)
# MADE network is much more powerful. 
#layer = MADE([batch_size, sequence_length, vocab_size], vocab_size, [nh, nh, nh])

```

**Comment by yalidu** [comment]
Thanks for your replies. That helps solve the problem!

**Comment by TrentBrick** [comment]
Glad to hear that worked for you! :)
