### ISSUE TITLE
Autoregressive base distribution

### ISSUE THREAD

**Issue by yannadani** [TrentBrick/PyTorchDiscreteFlows#4]
Hey!

I was looking into the replication of some of the other experiments in the paper and found that they have always used autoregressive base with autoregressive flow. Do you have any idea how they are exactly implemented? (The only thing the paper says is that its a autoregressive categorical distribution and for experiments with full-rank discrete distribution they have said they use transformers).

**Comment by TrentBrick** [comment]
Hey @yannadani sorry for the very slow reply this slipped through and starting grad school has been crazy right now. Given that you closed this issue did you figure it out? Without looking at the paper I think they learn the base distribution and use one of the autoregressive flow models like IAF?
