### ISSUE TITLE
Updating scale network

### ISSUE THREAD

**Issue by ZhaoxuanZhu** [TrentBrick/PyTorchDiscreteFlows#5]
Hello Trenton, 

Thank you for the awesome work and effort here. Have you tried to turn the scale update enabled(having $\sigma \neq 1$)? I have a problem with ~100 variables and ~40 classes, in which I am concerned that having the scale fixed can result in a low approximation capability. 

When I try to update the scale, I have this error reported: `ValueError: Inverse for 0 modulo 37 does not exist.` In the paper, the author mentioned that "For the scale, we add a mask whose elements are negative infinity on non-invertible values such as 0." (right above equation (6)), but I cannot find the related implementation in either of your or the TensorFlow implementations.

I have two additional observations:
1.  It seems like you and the author of the paper [edward2 discrete layer implementation](https://github.com/google/edward2/blob/a0f683ffc549add74d82405bc81073b7162cd408/edward2/tensorflow/layers/discrete_flows.py) implement the "forward" and "reverse" call in an opposite way. Any specific reason?
2. The original TensorFlow implementation uses tf_func in [utils](https://github.com/google/edward2/blob/a0f683ffc549add74d82405bc81073b7162cd408/edward2/tensorflow/layers/utils.py), whereas you used a python implementation. I believe the original one could benefit more from the gpu parallelization more. I can work on creating the PyTorch equivalency these days. 

Thanks,
Zhaoxuan

**Comment by TrentBrick** [comment]
Hi Zhaoxuan, 

Thanks for your post. 

I did not try more sophisticated scale updates and am not actively working on this implementation any longer so am not sure I can help with this! Apologies and if you find a solution please submit a PR. 

Regarding your other two observations:

1. Under ReadMe implementation details: "Going from Andre Karpathy's notation, flow.reverse() goes from the latent space to the data and flow.forward() goes from the data to the latent space. This is the inverse of some other implementations including the original Tensorflow one."
2. If you create a GPU parallelized version that would be awesome!

Thanks and sorry to not be of more help,
Trenton

**Comment by ZhaoxuanZhu** [comment]
No worries. This work has helped me a lot.
