### ISSUE TITLE
Issue with Example 'Fig2Replication'

### ISSUE THREAD

**Issue by damianoazzolini** [TrentBrick/PyTorchDiscreteFlows#6]
Hi,
I'm trying to run the example 'Fig2Replication', but I get some errors in the part 'Fit model'.
The first is `TypeError: 'module' object is not callable` that comes from line 119 of `disc_utils.py`.
This can be fixed (I suppose) by replacing `torch.fft` with `torch.fft.fft` (also at line 120).
After that, however, there is an error at line 121: `IndexError: index 1 is out of bounds for dimension 1 with size 1`.

Any idea how to fix it?
Thanks

**Comment by TrentBrick** [comment]
Hi thanks for your issue and sorry for the slow reply!

What version of Pytorch are you using? It seems like a package issue. If you try PyTorch 1.2.0 then does it work?

**Comment by damianoazzolini** [comment]
I get:
```
>>> import torch; print(torch.__version__)
1.9.0+cu102
```
so 1.9. Currently I cannot downgrade to version 1.2.0...

**Comment by TrentBrick** [comment]
I'm pretty sure it's a package issue. I haven't worked with FFT in a while and am not sure how to fix your particular bug. Apologies! If you do get a solution consider posting it here for others to find!

**Comment by damianoazzolini** [comment]
I think there is indeed some package issues due to version changing: https://github.com/pytorch/pytorch/issues/49637

**Comment by TrentBrick** [comment]
Well spotted and hopefully this gets resolved for future compatibility

**Comment by juancamilog** [comment]
This is an easy fix: the api is greatly simplified since complex numbers are supported out of the box (dtype complex64). `one_hot_add` becomes `torch.fft.ifft(torch.fft.fft(inputs) * torch.fft.fft(shift)).real`, which is pretty much the same as in the edward implementation

**Comment by TrentBrick** [comment]
@juancamilog thanks for sharing this! Going to close this but will point to your answer for anyone using 1.9 or higher.
